#ifndef TCONVERTER
#define TCONVERTER 1

/*
    Converter class
*/

#include <vector>

#include <TFile.h>
#include <TTree.h>
#include <TH1.h>
#include <TH2.h>
#include <TH3.h>

#include "TSDFReader.hpp"
#include "TBlockPlainMesh.hpp"
#include "TMeshValue.hpp"
#include "TMacroParticle.hpp"


class TConverter
{
public:
   TConverter(TSDFReader *reader);
   ~TConverter();

   void GetData();
   
private:
   TSDFReader *fReader;

   TFile *fOutput;
   TTree *fTree;
   

   
   
   void SaveTree();
   
   Int_t GetBlockIndex(TString ID);

   // Mesh values
   TMeshValue *fMeshValue;
   void ReadMeshGrid();
   void GetMeshData();
   TH1 *GetMeshHis(TString blockName, TString hisName, TString hisTitle);

   // Parameters for histogram.  Its will be generated by grid information
   Double_t fHisMin[3];
   Double_t fHisMax[3];
   TString fHisLabel[3];
   TString fHisUnit[3];
   Double_t fHisBinWidth[3];

   // Particle values
   std::vector<std::vector<TMacroParticle>> fMacroPar;
   void FindPar();

   std::vector<TString> fParName;
};


#endif

