#ifndef TCONVERTER
#define TCONVERTER 1

/*
    Converter class
*/

#include <TFile.h>
#include <TTree.h>
#include <TH1.h>
#include <TH2.h>
#include <TH3.h>

#include "TSDFReader.hpp"
#include "TBlockPlainMesh.hpp"
#include "TFieldValue.hpp"


class TConverter
{
public:
   TConverter(TSDFReader *reader);
   ~TConverter();

   void GetData();
   
private:
   TSDFReader *fReader;

   TFile *fOutput;
   TTree *fTree;
   
   TFieldValue *fFieldValue;
   
   void SaveTree();
   
   Int_t GetBlockIndex(TString ID);

   void ReadFieldGrid();

   void GetFieldData();
   TH1 *GetFieldHis(TString blockName, TString hisName, TString hisTitle);

   // Parameters for histogram.  Its will be generated by grid information
   Double_t fHisMin[3];
   Double_t fHisMax[3];
   TString fHisLabel[3];
   TString fHisUnit[3];
   Double_t fHisBinWidth[3];
};


#endif

