#ifndef TMESHVALUE
#define TMESHVALUE 1

/*
    Data class for mesh values.
    And also constants and Derived variables
    Class name is not so good.
*/

#include <vector>

#include <TH1.h>
#include <TH2.h>
#include <TH3.h>

#include "TSDFReader.hpp"

class TMeshValue
{
public:
   TMeshValue(TSDFReader *reader);
   ~TMeshValue();

   void Save();
   
   void ReadMeshGrid();
   void GetMeshData();

private:
   TSDFReader *fReader;
   
   // Mesh valiables
   // TH1D, TH2D, or TH3D
   TH1 *fEx;
   TH1 *fEy;
   TH1 *fEz;
   
   TH1 *fBx;
   TH1 *fBy;
   TH1 *fBz;

   TH1 *fJx;
   TH1 *fJy;
   TH1 *fJz;

   // Derived variables
   // NYI
   TH1 *fEkBar;
   TH1 *fEkFlux;
   TH1 *fMassDensity;
   TH1 *fChargeDensity;
   TH1 *fNumberDensity;
   TH1 *fPoyntFlux;
   std::vector<TH1*> Temperature;

   // For getting mesh values
   TH1 *GetMeshHis(TString blockName, TString hisName, TString hisTitle);

   // Parameters for histogram.  Its will be generated by grid information
   Double_t fHisMin[3];
   Double_t fHisMax[3];
   TString fHisLabel[3];
   TString fHisUnit[3];
   Double_t fHisBinWidth[3];

};

#endif
